server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定服务名 用于微服务调用
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mnn520
    url: jdbc:mysql://134.175.46.71:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
  jpa:
  database: MySQL
  show‐sql: true
  generate‐ddl: true