server: 
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.46.71:3306/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: mnn520
  jpa: 
    database: MySQL
    show-sql: true
