server: 
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.46.71:3306/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: mnn520
  jpa: 
    database: MySQL
    show-sql: true
jwt:
 config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true