server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.46.71:3306/tensquare_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: mnn520
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 134.175.46.71
  rabbitmq:
    host: 134.175.46.71

jwt:
 config:
    key: itcast
    ttl: 3600000